name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  coverage-22:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python_version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12-dev"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
          cache: 'pip' # caching pip dependencies
      - name: python package installation
        run: |
          pip install -e.[dev]
      - name: coverage run setup.py test
        run: |
          coverage run setup.py test
      - name: coverage report
        run: |
          coverage report

  mypy-22:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python_version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12-dev"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
          cache: 'pip' # caching pip dependencies
      - name: python package installation
        run: |
          pip install -e.[dev]
      - name: mypy yanico/
        run: |
          mypy yanico/

  pylint-22:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python_version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12-dev"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
          cache: 'pip' # caching pip dependencies
      - name: python package installation
        run: |
          pip install -e.[dev]
      - name: pylint setup.py tests/ yanico/
        run: |
          pylint setup.py tests/ yanico/

  rst2html5-22:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python_version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12-dev"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
          cache: 'pip' # caching pip dependencies
      - name: python package installation
        run: |
          pip install -e.[docs]
      - name: rst2html5.py --strict README.rst >/dev/null
        run: |
          rst2html5.py --strict README.rst >/dev/null

  build-22:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python_version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12-dev"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
          cache: 'pip' # caching pip dependencies
      - name: python package installation
        run: |
          pip install -e.
          pip install build
      - name: python -m build
        run: |
          python -m build
