name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  coverage-24:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python_version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
          cache: 'pip' # caching pip dependencies
      - name: python package installation
        run: |
          pip install -e.[dev]
      - run: coverage run -m pytest
      - run: coverage report

  mypy-24:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python_version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
          cache: 'pip' # caching pip dependencies
      - name: python package installation
        run: |
          # Cannot find implementation or library stub for module named "importlib_metadata" (python_version < "3.10")
          pip install -e.[dev] importlib-metadata
      - run: mypy yanico/ --install-types

  pylint-24:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python_version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
          cache: 'pip' # caching pip dependencies
      - name: python package installation
        run: |
          pip install -e.[dev]
      - run: pylint setup.py tests/ yanico/

  rst2html5-24:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python_version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
          cache: 'pip' # caching pip dependencies
      - name: python package installation
        run: |
          pip install -e.[dev]
      - run: rst2html5 --strict README.rst >/dev/null

  black-24:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python_version:
          - "3.13"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
          cache: 'pip' # caching pip dependencies
      - name: python package installation
        run: |
          pip install -e.[dev]
      - run: black .

  build-24:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python_version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
          cache: 'pip' # caching pip dependencies
      - name: python package installation
        run: |
          pip install -e.
          pip install build
      - run: python -m build
